### ISSUE TITLE
TextBuffer `raw` should not call free

### ISSUE THREAD

**Issue by sebastianbaginski** [cogneco/ooc-kean#1059]
```ooc
TextBuffer: cover {
	raw: Char* { get {
		result := this _backend pointer as Char*
		this free(Owner Receiver)
		result
	}}
	operator [] (index: Int) -> Char { this raw[index] }
	operator []= (index: Int, value: Char) { this raw[index] = value }
}
```
Currently it is not used anywhere, but I'm sure as soon as people starts using it they will notice crashes or weird results related to accessing non existing memory.
So currently it saves the pointer to internal buffer in `result`, frees it and then returns the saved pointer. Which now of course points to the already freed memory segment.
This `take / free` approach works nice if you return a copy of existing object. 
Here both of the `operator []` function can potentially read from / write to invalid memory : 
```ooc
t := Text new("text") copy()
t _buffer[0] = 'a' //
    // --> calls: 
   // t raw(0)
   ////      --> result := this pointer
   ////      --> this free() --> free(this pointer)
   ////      --> result[0] --> this pointer[0] !!!
```

**Comment by sebastianbaginski** [comment]
@marcusnaslund @simonmika

**Comment by marcusnaslund** [comment]
This is probably just an unfortunate accident, it shouldn't free.

**Comment by tomasmahlberg** [comment]
Actually, I think @simonmika deliberately let `raw` free the buffer to make it consistent with the rule that all methods and operators should free objects with no claimed ownership. However, I made the similar `elements` property in `FloatMatrix` not free the buffer because I thought it made more sense to not free something that you just requested the pointer to, so there's some selected consistency going on here. :) Maybe we should come to a consensus on what to do here?

In any case, I think that we want to have the index operator (but not the assign operator) free the back-end there hough?

**Comment by sebastianbaginski** [comment]
> @simonmika deliberately let raw free the buffer to make it consistent with the rule that all methods and operators should free objects with no claimed ownership

I understand, but this makes `raw` useless. I can't think of single use case when you'd want to store a pointer to deallocated memory.

>  I think that we want to have the index operator (but not the assign operator) free the back-end there

Yes, I think this is reasonable.

**Comment by simonmika** [comment]
Then remove `raw`.
