### ISSUE TITLE
Type inference problems with ThreadPool getFuture()

### ISSUE THREAD

**Issue by marcusnaslund** [cogneco/ooc-kean#556]
Just like in `start()` in `Future`, `getFuture()` of `ThreadPool` needs to be like this:
```ooc
getFuture: func <T> (T: Class, action: Func -> T) -> Future<T> {
//... same as before
}
```
This is to avoid the type inference madness in rock.

**Comment by ziquanyu** [comment]
Rock can not figure out the type of T as input.

**Comment by marcusnaslund** [comment]
Yeah @fredrikbryntesson told me. The alternative as I see it is to pre-allocate space somewhere, store the data there from inside the func instead of returning anything (i.e. a Promise).

**Comment by marcusnaslund** [comment]
But this opens up another question - do we still want `Future`...?

**Comment by ziquanyu** [comment]
@simonmika , what do you say about this bug?

**Comment by ziquanyu** [comment]
@simonmika @marcusnaslund @fredrikbryntesson Pre-allocate + getPromise() can avoid this rock generic bug.

**Comment by simonmika** [comment]
I don't like preallocation and I need clearer information to make a decision. From this discussion it is not clear what works and not.

**Comment by ziquanyu** [comment]
The following is how we use it when it's working.

future2 := pool getFuture(func { for (i in 0 .. 100_000_000) { } "pass" } )
result2 := future2 wait("fail")
result2 is "pass"

++++++++++++++++++++++++++++++++++++++++

The following is how we use it when it's working.

future2 := pool getFuture(func { for (i in 0 .. 100_000_000) { word := "pass" } word } )
result2 := future2 wait("fail")
result2 is "pass"

++++++++++++++++++++++++++++++++++++++++

The following is how we use it when it's not working.

word := "pass"
future2 := pool getFuture(func { for (i in 0 .. 100_000_000) { } word } )   <- it crushes here because rock can not figure out what is "word".
result2 := future2 wait("fail")
result2 is "pass"

++++++++++++++++++++++++++++++++++++++++

The following is how we use it when it's not working.

len := 1000000
future2 := pool getFuture(func { for (i in 0 .. len) { word := "pass" } word } )   <- it crushes here because rock can not figure out what is "len".
result2 := future2 wait("fail")
result2 is "pass"

**Comment by simonmika** [comment]
Can we create an overload like this:
```ooc
getFuture: func ~closure <T, S> (action: Func(S) -> T, closure: S) -> Future<T> {
//... same as before
}
```

**Comment by marcusnaslund** [comment]
@thomasfanell Will the new version of rock solve the problems here?

**Comment by thomasfanell** [comment]
I have not tested this particular case, but by the looks of it, yes.

**Comment by marcusnaslund** [comment]
With the new rock, this works perfectly just as it is :D
