### ISSUE TITLE
ByteBuffer member names

### ISSUE THREAD

**Issue by davidhesselbom** [cogneco/ooc-kean#698]
#559 cleans up `ByteBuffer` but introduces some names that could be improved on:

- `_owner` is a `Bool` for whether the buffer owns its data or not, but the name isn't quite spot-on.
- `_forceFree` is another `Bool` for whether the buffer should be (if `true`) freed or (if `false`) recycled/recovered or whatever the specialized implementation does when someone calls its `free` function.
- `forceFree` is a function that sets `_forceFree` to `true` before calling the `free` function. This works, but I don't think whoever uses a `ByteBuffer` should be in control of how it handles its data - that behavior should be encapsulated, so this function shouldn't be there.

**Comment by emilwestergren** [comment]
Regarding `_owner` I'm fine with any of these, I think we've already spent too much time on it:
* `_ownsBuffer`
* `_ownsMemory`
* `_isOwner`
* `_freeBackend`
* `_freeContent`
* `_freeMemory`

**Comment by sebastianbaginski** [comment]
I vote for consistency with `Vector`. Not necessarily `_freeContent` as it is in Vector, but I think it should be the same in both classes.

**Comment by emilwestergren** [comment]
I agree that `forceFree` should be removed from the public API. The reason for adding this was to handle memory leaks when using `_RecoverableByteBuffer`. For these buffers, the user can provide a callback which will be called when the buffer is freed. The problem is if the `_RecoverableByteBuffer` actually should be completely freed, who takes care of this?

* The callback returns a bool which decides if the whole buffer object will be freed after the callback
* A `_RecoverableByteBuffer` is **always** freed after the callback
* A specialized `ByteBuffer` is added for this use case

**Comment by emilwestergren** [comment]
Naming suggestions please:
`_forceFree` - private function in `_RecyclableByteBuffer` which forces a complete free.
`_owner` - flag which determines if the backend memory shall be freed when the ByteBuffer is freed.
I'll include them in the PR: https://github.com/cogneco/ooc-kean/pull/850
