### ISSUE TITLE
Text test has invalid delete/free bug again

### ISSUE THREAD

**Issue by sebastianbaginski** [cogneco/ooc-kean#865]
```ooc
			text = tb join(';')
			expect(text == t"1;2;3")
			tb free()
			text free()
```
`text free()` causes double free/delete. 
Probably `text` is already freed by the `operator ==` above.
@tomasmahlberg @simonmika  I can make a PR with fix if you can only confirm that the last `free` should not be there.

**Comment by sebastianbaginski** [comment]
I think this was it, https://github.com/cogneco/ooc-kean/pull/866

**Comment by tomasmahlberg** [comment]
It seems like `join` in `TextBuilder` again calls this constructor in `Text`: `init: func@ (=_buffer)` (like in #836), so the result of the call to `join` will have owner set to `Receiver` and will hence be freed by the equality comparison. I think the general recommendation is to `take()` when you assign to a variable, so I would suggest changing `text = tb join(';')` to `text = tb join(';') take()` instead of removing the call to `free`.

**Comment by sebastianbaginski** [comment]
OK thanks.
